# Basic information
baseURL = 'https://benjamin7king.github.io/' # Should be updated to your domain
languageCode = 'en-us'
theme="archie"

# Metadata to edit
title = 'Kreate Community'
copyright = "Â© KREATE"
blogTitle='Check out my blog:'

# For code highlighting
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Social media for footer icons, could add more
[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/amherstcollege"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/amherstcollege"

# Menu items
[[menu.main]]
name = "home"
url = "/"
weight = 1 # lower number sorts them to the left

[[menu.main]]
name = "blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "tags"
url = "/tags"
weight = 3
